import { useEffect, useState } from "react";
import { Download, FileText, Plus, RefreshCw } from "lucide-react";
import { api, type OptimizationReport } from "../lib/api";

type Toast = (title: string, body: string, tone?: "success" | "info") => void;
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export function ReportsWorkspacePage({ toast }: { toast: Toast }) {
  const [reports, setReports] = useState<OptimizationReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [error, setError] = useState("");

  const refresh = async () => {
    setLoading(true);
    try {
      setReports(await api.reports());
      setError("");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Could not load saved reports.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void refresh(); }, []);

  const generate = async () => {
    setWorking(true);
    try {
      const report = await api.createReport();
      setReports((current) => [report, ...current]);
      toast("Report generated", "The report snapshot was calculated from current API data and saved to the workspace.", "success");
    } catch (reason) {
      toast("Report generation failed", reason instanceof Error ? reason.message : "The report could not be saved.");
    } finally {
      setWorking(false);
    }
  };

  const exportCsv = async () => {
    setWorking(true);
    try {
      const blob = await api.exportReportCsv();
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "smartsize-optimization-report.csv";
      link.click();
      URL.revokeObjectURL(url);
      toast("CSV exported", "The report was generated from current backend recommendation data.", "success");
    } catch (reason) {
      toast("CSV export failed", reason instanceof Error ? reason.message : "The report could not be exported.");
    } finally {
      setWorking(false);
    }
  };

  return <div className="page-wrap fade-up">
    <div className="mb-7 flex items-start justify-between gap-4 mobile-stack">
      <div>
        <div className="eyebrow mb-2">Reporting · Workspace data</div>
        <h1 className="page-title">Reports</h1>
        <p className="page-subtitle mt-2 max-w-2xl">Generate a saved snapshot from current backend data or export recommendation records as CSV. PDF export is not available.</p>
      </div>
      <div className="flex gap-2">
        <button className="btn btn-ghost" onClick={() => void exportCsv()} disabled={working}><Download size={14} /> Export CSV</button>
        <button className="btn btn-primary" onClick={() => void generate()} disabled={working}>{working ? <RefreshCw size={14} className="animate-spin" /> : <Plus size={14} />} Generate report</button>
      </div>
    </div>
    {error && <div role="alert" className="mb-5 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>}
    <section className="card overflow-hidden">
      <div className="border-b border-slate-100 p-5">
        <h2 className="font-semibold text-slate-800">Saved report snapshots</h2>
        <p className="mt-1 text-xs text-slate-500">Each report retains the summary calculated at generation time.</p>
      </div>
      {loading ? <div className="p-8 text-center text-sm text-slate-500">Loading saved reports…</div>
        : reports.length === 0 ? <div className="p-8 text-center text-sm text-slate-500">No reports yet. Generate a snapshot to record current workspace totals.</div>
          : <div className="divide-y divide-slate-100">{reports.map((report) => <article key={report.id} className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between">
            <div className="flex min-w-0 items-start gap-3">
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><FileText size={16} /></span>
              <div className="min-w-0"><h3 className="truncate text-sm font-semibold text-slate-800">{report.name}</h3><p className="mt-1 text-xs text-slate-500">Generated by {report.createdBy} · {new Date(report.createdAt).toLocaleString()}</p></div>
            </div>
            <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-xs sm:grid-cols-4">
              <div><dt className="text-slate-400">Resources</dt><dd className="mt-1 font-semibold text-slate-700">{report.summary.totalResources}</dd></div>
              <div><dt className="text-slate-400">Open recommendations</dt><dd className="mt-1 font-semibold text-slate-700">{report.summary.openRecommendations}/{report.summary.totalRecommendations}</dd></div>
              <div><dt className="text-slate-400">Monthly opportunity</dt><dd className="mt-1 font-semibold text-emerald-700">{money(report.summary.potentialMonthlySavings)}</dd></div>
              <div><dt className="text-slate-400">Verified savings</dt><dd className="mt-1 font-semibold text-slate-700">{money(report.summary.verifiedSavings)}</dd></div>
            </dl>
          </article>)}</div>}
    </section>
    <div className="mt-4 flex justify-end"><button className="btn btn-ghost" onClick={() => void refresh()} disabled={loading}><RefreshCw size={14} /> Refresh reports</button></div>
  </div>;
}
